config/routes.rb
Rails.application.routes.draw do
  
  resources :role_types
  resources :people

  get 'statics/home'
  get 'statics/help'
  get 'statics/about'

  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users

end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/role_type.rb
class RoleType < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate_user!, :set_person, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:firstName, :lastName)
    end
end

app/controllers/role_types_controller.rb
class RoleTypesController < ApplicationController
  before_action :set_role_type, only: [:show, :edit, :update, :destroy]

  # GET /role_types
  # GET /role_types.json
  def index
    @role_types = RoleType.all
  end

  # GET /role_types/1
  # GET /role_types/1.json
  def show
  end

  # GET /role_types/new
  def new
    @role_type = RoleType.new
  end

  # GET /role_types/1/edit
  def edit
  end

  # POST /role_types
  # POST /role_types.json
  def create
    @role_type = RoleType.new(role_type_params)

    respond_to do |format|
      if @role_type.save
        format.html { redirect_to @role_type, notice: 'Role type was successfully created.' }
        format.json { render :show, status: :created, location: @role_type }
      else
        format.html { render :new }
        format.json { render json: @role_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /role_types/1
  # PATCH/PUT /role_types/1.json
  def update
    respond_to do |format|
      if @role_type.update(role_type_params)
        format.html { redirect_to @role_type, notice: 'Role type was successfully updated.' }
        format.json { render :show, status: :ok, location: @role_type }
      else
        format.html { render :edit }
        format.json { render json: @role_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /role_types/1
  # DELETE /role_types/1.json
  def destroy
    @role_type.destroy
    respond_to do |format|
      format.html { redirect_to role_types_url, notice: 'Role type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role_type
      @role_type = RoleType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_type_params
      params.require(:role_type).permit(:roleName)
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/role_types_helper.rb
module RoleTypesHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Org2 Directory" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Org2 Directory" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstName %><br>
    <%= f.text_area :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_area :lastName %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.firstName %></td>
        <td><%= person.lastName %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @person.firstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @person.lastName %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/role_types/_form.html.erb
<%= form_for(@role_type) do |f| %>
  <% if @role_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role_type.errors.count, "error") %> prohibited this role_type from being saved:</h2>

      <ul>
      <% @role_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :roleName %><br>
    <%= f.text_field :roleName %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/role_types/edit.html.erb
<h1>Editing Role Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @role_type %> |
<%= link_to 'Back', role_types_path %>

app/views/role_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Role Types</h1>

<table>
  <thead>
    <tr>
      <th>Rolename</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @role_types.each do |role_type| %>
      <tr>
        <td><%= role_type.roleName %></td>
        <td><%= link_to 'Show', role_type %></td>
        <td><%= link_to 'Edit', edit_role_type_path(role_type) %></td>
        <td><%= link_to 'Destroy', role_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role type', new_role_type_path %>

app/views/role_types/new.html.erb
<h1>New Role Type</h1>

<%= render 'form' %>

<%= link_to 'Back', role_types_path %>

app/views/role_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rolename:</strong>
  <%= @role_type.roleName %>
</p>

<%= link_to 'Edit', edit_role_type_path(@role_type) %> |
<%= link_to 'Back', role_types_path %>

app/views/statics/about.html.erb
<h1>Statics#about</h1>
<p>Find me in app/views/statics/about.html.erb</p>

app/views/statics/help.html.erb
<h1>Statics#help</h1>
<p>Find me in app/views/statics/help.html.erb</p>

app/views/statics/home.html.erb
<h1>Statics#home</h1>
<p>Find me in app/views/statics/home.html.erb</p>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>